version: '3.8'
services:
   web:
       build: .
       command: sh -c "dvc pull && python src/preprocessor.py && python src/train.py && python src/predict.py && python -m unittest discover -s src/test/"
       ports:
           - 8000:8000
       image: danjiii/bcc-classification:latest