pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('dockerhub')
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}

    stages {
        stage('Login') {
            steps {
                sh "sudo docker login -u ${DOCKERHUB_USR} -p ${DOCKERHUB_PSW}"
            }
        }

        stage('Pull image'){
            steps{
                sh "sudo docker pull danjiii/bcc-classification:latest"
            }
        }

        stage('Run container'){
            steps{
                sh "sudo docker run --name lab1 -d danjiii/bcc-classification:latest"
            }
        }
    }

    post {
        always {
            sh "sudo docker stop lab1 && sudo docker logout"
        }
    }
}