pipeline {
    agent any

    triggers {
        pipelineTriggers([cron('H/30 * * * *'), githubPush()])
    }

    environment {
        DOCKERHUB = credentials('dockerhub')
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}

    stages {
        stage('Hello') {
            steps {
                script {
                    echo "Hello world"
                    sh ls
                }
            }
        }
    }
}
