pipeline {
    agent any

    triggers {
        cron('H/30 * * * *')
        githubPush()
    }

    environment {
        DOCKERHUB = credentials('dockerhub')
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}

    stages {
        stage('Hello') {
            steps {
                script {
                    echo "Hello world"
                    sh "ls"
                }
            }
        }

        stage('Login'){
            steps {
                echo "%DOCKERHUB_USR%"
                sh "docker login -u %DOCKERHUB_USR% -p %DOCKERHUB_PSW%"
            }
        }
    }
}
