pipeline {
    agent any

    triggers {
        cron('H/30 * * * *')
        githubPush()
    }

    environment {
        DOCKERHUB = credentials('dockerhub')
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
	}

    stages {
        stage('Clone github repository'){
            steps {
                cleanWs()
                sh "git clone -b main https://github.com/A6u7H/news_classification"
                sh "dir"
			}
        }

        stage('Login'){
            steps {
                sh "sudo docker login -u ${DOCKERHUB_USR} -p ${DOCKERHUB_PSW}"
            }
        }

        stage('Create and run docker container') {
            steps {
                script {
                    sh "cd news_classification"
                    sh "dir"
                    try {
                        sh "docker compose build"
                    }
                    finally {
                        sh "docker compose up -d"
                    }
                }
            }
        }
    }
}